replicaCount: 1

frontend:
  image:
    repository: ghcr.io/syf3rr/devops-k8s-pet-frontend
    tag: latest
  port: 80

backend:
  image:
    repository: ghcr.io/syf3rr/devops-k8s-pet-backend
    tag: latest
  port: 5000

postgres:
  image:
    repository: postgres
    tag: 15-alpine
  port: 5432
  dbName: auth_db

ingress:
  enable: true
  host: demo-app.local