apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: demo-app-postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-postgres-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-init-script
          configMap:
            name: {{ .Release.Name }}-postgres-init-cm

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgres-svc"
            
            - name: DB_PORT
              value: {{ .Values.postgres.port | quote }}
            
            - name: DB_NAME
              value: {{ .Values.postgres.dbName | quote }}
            
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: demo-app-postgres-secret
                  key: postgres-user
            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-postgres-secret
                  key: postgres-password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}