---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-app-backend-secret
  namespace: default
spec:
  encryptedData:
    jwt-secret: AgCY5IfWIOZtOXe1b72/ryqg/Y/qEwaWTjPO+jiQbqZJjw3JjxPeArupiBFo5cGI4IQvzoRr+AtHgjh1nWDI6cNSFyQ+X22hCXTLFS0iVIAnHKGm9dWJ2mwMSuHJNnY/eQaAfIbXLTydAVQrEybKava6UbcB5fU0fnYaASj7cH1PqWQBrcjBSygtxfZfOnPEncNLRh+SHdUO/6o6tMmkp2diICZppwSKqsCFgqXfp9yl3qc+qgIy8ybgqEmcC2O4tLkupipIqsvXUGTdGv0AZx5JERrsgUO+z89n/p/HpfdYum1qSMqcUM45Xobepi1Xp2ICJUpF3orONOZyca8DL91X8l1kLk1z2Peo+m9U1b04MRZA1DMz6GoNb3OIar0dXs/gDcznW8daHtEEK0vGucz4KlALlnj99Juzj9bXFBZY1CF6AaZqhaqx5WOESqrhfdqYj7gfKHzolgZnRSPENRZK7JZl9XLkGEiDYehn1WgsqKOCsncJGJBvTymPl/gvYqLOICOkKeYCxIwGrZKCd1CWrq+VhGhtFVTFx+0wCdTkMiVBIlgPGrwukNI3LbZsFYH+kK3cAeZDrvuKW66mQGc5EO+bWDPUNfRbCzB6PPtt6Ma5cOZPseBlC9Nzp153aX/5VX9gwDK2Z28Lj7tTMT7+wwUV8XHwttWJeNrUTi+5fcaj8Jkz5gNFJcepJaL74RcOTDRyGR5QdPNiwJqYBNk399HxT/gmzzoNiOSMLw==
  template:
    metadata:
      creationTimestamp: null
      name: demo-app-backend-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-app-postgres-secret
  namespace: default
spec:
  encryptedData:
    postgres-password: AgBCEo2Xxm8MheUSANWeYMdymnBYCw4qc63oowefp72xS3iQKv1F8tZ+v9/qqc9FKkK36x6ewGCFK6nms++e9z5lrWjK2EjhBYOTbA00y+HESJ6V3wFXbSaFQs8/qqI2DmDJBSH9yrgy8KRQBthEf8pOMPtpckbFIPYlFREtWnzXWGKOLmY1NqRXWBn3P5GvnTasd9tBLI10nS7myJ8rOqKgejKuS8BXpIjwBISj/EQNEEyQc7YhkhM1hsPh9vPUy0/szDvDQHIdNJHt6KOppALlIcp5BAnVXC9VxrTcMlPR04sul5OSyY5xSYy/cQJPYcEqs/pliR0mobt0zfIfmGEcXZP7RNaIjkh/OLNrT0vCIuXMRRXGC/wDtYAFVUefa07sa6/tGe8zucwUbAShqO5nEoyXl4gVCeBAhMDradsQe7N2r6feeTlOg3cvdDZpputD0e6OE3SlNJmAAYafd2CBd3e+2N9cxaXQCSSuMq/8OIafKWfnyRJuj8G/nF3+m+B5FIWItR0Lczct6nqVYw8shyma0mL31nuzBFY1FRrlbknLn98B0zYP3fZi0OVpumkso0kNaqLRbUPgTzlhyy0tRGoT0Kl0JiiGexDRg96Cbsoac7KOkJA368Nu48RYMvPS+NVZ+hcn80Bc7Viek3hwVbbbBQF0HxAYaC79BzRHlvZZ/CZIl8j6ql8FWvnXNWx2/Cu73KjS9QnD6XbAlVCti1DH5FGOJPXmjFWy
    postgres-user: AgBVrtse7BlRNEwDdcXLODI3hHu+3pdS9KSW0l0nBwrNfrvuJb9FAC9uzqpzNoqtsqVs7Zm6KPdVjBHhINaLIfwjnwZuXT5bH+kVKSEMJciCvhwkZstnzB3RCEFC6y8flFXruNprO/62P+cba/7l2JwdwS9bNDsqT2oipaw5W1sZfEIBJ2T0YxTMCJIrylyr9cRB2HBDSsOCPn50sqGyR2rni/JlmdMsM18kscabNcuHEGUBAN78NGZsKaLLGrsKLhYVLYfyHk3/9l2nXTwE/JMR3sQdBeQmTEy5sOd2xNmnDKCoPI9zMmUpIk0rK4rxo9YK6vOjOlTlxT/vCAmT9tju8Pz5AzR3+T7qc33SOekh35VRyCnqNATnZ0xmp7JMq8i/Gt5OBr9RUHO8y1ZYcsMPXnZuroTtpKiZ+tCMerE/2bG3eO5jzaDN7mLsmfGKg0girQKGcISLFuQi0I1dORDW1Urr050Hh4PmltmRs+AQtA3/kAihmXWKQCUkZerKwXWG+r8Ce2zuVqvK96mm62nLbcrQSpbezqniq6SLkfZAIPusnuZIPrVqBQp+ySaODhWC0obSA6tE0V8ptiET19ULvx22oxWY87ZD6IFoYTcnTe4vrG6aT9EPH7qw5ZbquOd1YLUh++euOiB522JGDr07zEFDD+vw3Fo2K8FXkquGadIryC8PzLoKMbYpfICGdpOPDwvuEXSvueee/x3i
  template:
    metadata:
      creationTimestamp: null
      name: demo-app-postgres-secret
      namespace: default
    type: Opaque
