apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector: 
    app: {{ .Release.Name }}-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  selector:
    app: {{ .Release.Name }}-backend

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: {{ .Release.Name }}-frontend