loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
  promtail:
    enabled: true
  grafana:
    enabled: false
    additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack:3100
      jsonData:
        maxLines: 1000